/* Automatically @generated by tree-sitter v0.25.8 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 33
#define LARGE_STATE_COUNT 5
#define SYMBOL_COUNT 25
#define ALIAS_COUNT 0
#define TOKEN_COUNT 15
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_SLASH_STAR_STAR = 1,
  anon_sym_STAR_SLASH = 2,
  anon_sym_ATfunction = 3,
  anon_sym_ATclass = 4,
  anon_sym_ATparam = 5,
  anon_sym_DASH = 6,
  anon_sym_ATproperty = 7,
  anon_sym_ATreturns = 8,
  sym_doc_text = 9,
  anon_sym_LBRACE = 10,
  aux_sym_type_token1 = 11,
  anon_sym_RBRACE = 12,
  sym_identifier = 13,
  sym_description = 14,
  sym_source_file = 15,
  sym_doc_comment = 16,
  sym_function_tag = 17,
  sym_class_tag = 18,
  sym_param_tag = 19,
  sym_property_tag = 20,
  sym_returns_tag = 21,
  sym_type = 22,
  aux_sym_source_file_repeat1 = 23,
  aux_sym_doc_comment_repeat1 = 24,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_SLASH_STAR_STAR] = "/**",
  [anon_sym_STAR_SLASH] = "*/",
  [anon_sym_ATfunction] = "@function",
  [anon_sym_ATclass] = "@class",
  [anon_sym_ATparam] = "@param",
  [anon_sym_DASH] = "-",
  [anon_sym_ATproperty] = "@property",
  [anon_sym_ATreturns] = "@returns",
  [sym_doc_text] = "doc_text",
  [anon_sym_LBRACE] = "{",
  [aux_sym_type_token1] = "type_token1",
  [anon_sym_RBRACE] = "}",
  [sym_identifier] = "identifier",
  [sym_description] = "description",
  [sym_source_file] = "source_file",
  [sym_doc_comment] = "doc_comment",
  [sym_function_tag] = "function_tag",
  [sym_class_tag] = "class_tag",
  [sym_param_tag] = "param_tag",
  [sym_property_tag] = "property_tag",
  [sym_returns_tag] = "returns_tag",
  [sym_type] = "type",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_doc_comment_repeat1] = "doc_comment_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_SLASH_STAR_STAR] = anon_sym_SLASH_STAR_STAR,
  [anon_sym_STAR_SLASH] = anon_sym_STAR_SLASH,
  [anon_sym_ATfunction] = anon_sym_ATfunction,
  [anon_sym_ATclass] = anon_sym_ATclass,
  [anon_sym_ATparam] = anon_sym_ATparam,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_ATproperty] = anon_sym_ATproperty,
  [anon_sym_ATreturns] = anon_sym_ATreturns,
  [sym_doc_text] = sym_doc_text,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [aux_sym_type_token1] = aux_sym_type_token1,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_identifier] = sym_identifier,
  [sym_description] = sym_description,
  [sym_source_file] = sym_source_file,
  [sym_doc_comment] = sym_doc_comment,
  [sym_function_tag] = sym_function_tag,
  [sym_class_tag] = sym_class_tag,
  [sym_param_tag] = sym_param_tag,
  [sym_property_tag] = sym_property_tag,
  [sym_returns_tag] = sym_returns_tag,
  [sym_type] = sym_type,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_doc_comment_repeat1] = aux_sym_doc_comment_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_SLASH_STAR_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATfunction] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATclass] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATparam] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATproperty] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATreturns] = {
    .visible = true,
    .named = false,
  },
  [sym_doc_text] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_type_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_description] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_doc_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_function_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_class_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_param_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_property_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_returns_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_doc_comment_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 25,
  [31] = 28,
  [32] = 20,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(38);
      if (lookahead == '*') ADVANCE(3);
      if (lookahead == '-') ADVANCE(48);
      if (lookahead == '@') ADVANCE(11);
      if (lookahead == '{') ADVANCE(84);
      if (lookahead == '}') ADVANCE(88);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(89);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1);
      if (lookahead == '*') ADVANCE(86);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(85);
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(87);
      END_STATE();
    case 2:
      if (lookahead == '!') ADVANCE(54);
      if (lookahead == '*') ADVANCE(2);
      if (lookahead == '/') ADVANCE(40);
      if (lookahead == '@') ADVANCE(11);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      if (lookahead != 0) ADVANCE(83);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(3);
      if (lookahead == '-') ADVANCE(48);
      if (lookahead == '/') ADVANCE(40);
      if (lookahead == '@') ADVANCE(11);
      if (lookahead == '{') ADVANCE(84);
      if (lookahead == '}') ADVANCE(88);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == '!') SKIP(4);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(89);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(3);
      if (lookahead == '-') ADVANCE(48);
      if (lookahead == '@') ADVANCE(11);
      if (lookahead == '{') ADVANCE(84);
      if (lookahead == '}') ADVANCE(88);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(89);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(39);
      END_STATE();
    case 6:
      if (lookahead == '*') ADVANCE(2);
      if (lookahead == '@') ADVANCE(11);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      if (lookahead != 0 &&
          lookahead != '/') ADVANCE(83);
      END_STATE();
    case 7:
      if (lookahead == '*') ADVANCE(5);
      END_STATE();
    case 8:
      if (lookahead == 'a') ADVANCE(24);
      if (lookahead == 'r') ADVANCE(21);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(29);
      END_STATE();
    case 10:
      if (lookahead == 'a') ADVANCE(17);
      END_STATE();
    case 11:
      if (lookahead == 'c') ADVANCE(16);
      if (lookahead == 'f') ADVANCE(33);
      if (lookahead == 'p') ADVANCE(8);
      if (lookahead == 'r') ADVANCE(13);
      END_STATE();
    case 12:
      if (lookahead == 'c') ADVANCE(30);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(32);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(26);
      END_STATE();
    case 15:
      if (lookahead == 'i') ADVANCE(22);
      END_STATE();
    case 16:
      if (lookahead == 'l') ADVANCE(9);
      END_STATE();
    case 17:
      if (lookahead == 'm') ADVANCE(46);
      END_STATE();
    case 18:
      if (lookahead == 'n') ADVANCE(12);
      END_STATE();
    case 19:
      if (lookahead == 'n') ADVANCE(42);
      END_STATE();
    case 20:
      if (lookahead == 'n') ADVANCE(28);
      END_STATE();
    case 21:
      if (lookahead == 'o') ADVANCE(23);
      END_STATE();
    case 22:
      if (lookahead == 'o') ADVANCE(19);
      END_STATE();
    case 23:
      if (lookahead == 'p') ADVANCE(14);
      END_STATE();
    case 24:
      if (lookahead == 'r') ADVANCE(10);
      END_STATE();
    case 25:
      if (lookahead == 'r') ADVANCE(20);
      END_STATE();
    case 26:
      if (lookahead == 'r') ADVANCE(31);
      END_STATE();
    case 27:
      if (lookahead == 's') ADVANCE(44);
      END_STATE();
    case 28:
      if (lookahead == 's') ADVANCE(51);
      END_STATE();
    case 29:
      if (lookahead == 's') ADVANCE(27);
      END_STATE();
    case 30:
      if (lookahead == 't') ADVANCE(15);
      END_STATE();
    case 31:
      if (lookahead == 't') ADVANCE(35);
      END_STATE();
    case 32:
      if (lookahead == 't') ADVANCE(34);
      END_STATE();
    case 33:
      if (lookahead == 'u') ADVANCE(18);
      END_STATE();
    case 34:
      if (lookahead == 'u') ADVANCE(25);
      END_STATE();
    case 35:
      if (lookahead == 'y') ADVANCE(49);
      END_STATE();
    case 36:
      if (eof) ADVANCE(38);
      if (lookahead == '*') SKIP(37);
      if (lookahead == '/') ADVANCE(7);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(36);
      END_STATE();
    case 37:
      if (eof) ADVANCE(38);
      if (lookahead == '*') SKIP(37);
      if (lookahead == '/') ADVANCE(7);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == '!') SKIP(36);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR_STAR);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_STAR_SLASH);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_STAR_SLASH);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(83);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_ATfunction);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_ATfunction);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(83);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_ATclass);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_ATclass);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(83);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_ATparam);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_ATparam);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(83);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_ATproperty);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_ATproperty);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(83);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_ATreturns);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_ATreturns);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(83);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_doc_text);
      if (lookahead == '!') ADVANCE(54);
      if (lookahead == '*') ADVANCE(53);
      if (lookahead == '/') ADVANCE(41);
      if (lookahead == '@') ADVANCE(58);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(54);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(83);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_doc_text);
      if (lookahead == '*') ADVANCE(53);
      if (lookahead == '/') ADVANCE(83);
      if (lookahead == '@') ADVANCE(58);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(54);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(83);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_doc_text);
      if (lookahead == 'a') ADVANCE(71);
      if (lookahead == 'r') ADVANCE(68);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(83);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_doc_text);
      if (lookahead == 'a') ADVANCE(76);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(83);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_doc_text);
      if (lookahead == 'a') ADVANCE(64);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(83);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_doc_text);
      if (lookahead == 'c') ADVANCE(63);
      if (lookahead == 'f') ADVANCE(80);
      if (lookahead == 'p') ADVANCE(55);
      if (lookahead == 'r') ADVANCE(60);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(83);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_doc_text);
      if (lookahead == 'c') ADVANCE(77);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(83);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_doc_text);
      if (lookahead == 'e') ADVANCE(79);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(83);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_doc_text);
      if (lookahead == 'e') ADVANCE(73);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(83);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_doc_text);
      if (lookahead == 'i') ADVANCE(69);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(83);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_doc_text);
      if (lookahead == 'l') ADVANCE(56);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(83);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_doc_text);
      if (lookahead == 'm') ADVANCE(47);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(83);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_doc_text);
      if (lookahead == 'n') ADVANCE(59);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(83);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_doc_text);
      if (lookahead == 'n') ADVANCE(43);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(83);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_doc_text);
      if (lookahead == 'n') ADVANCE(75);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(83);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_doc_text);
      if (lookahead == 'o') ADVANCE(70);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(83);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_doc_text);
      if (lookahead == 'o') ADVANCE(66);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(83);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_doc_text);
      if (lookahead == 'p') ADVANCE(61);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(83);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_doc_text);
      if (lookahead == 'r') ADVANCE(57);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(83);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_doc_text);
      if (lookahead == 'r') ADVANCE(67);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(83);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_doc_text);
      if (lookahead == 'r') ADVANCE(78);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(83);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_doc_text);
      if (lookahead == 's') ADVANCE(45);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(83);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_doc_text);
      if (lookahead == 's') ADVANCE(52);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(83);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_doc_text);
      if (lookahead == 's') ADVANCE(74);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(83);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_doc_text);
      if (lookahead == 't') ADVANCE(62);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(83);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_doc_text);
      if (lookahead == 't') ADVANCE(82);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(83);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_doc_text);
      if (lookahead == 't') ADVANCE(81);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(83);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_doc_text);
      if (lookahead == 'u') ADVANCE(65);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(83);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_doc_text);
      if (lookahead == 'u') ADVANCE(72);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(83);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_doc_text);
      if (lookahead == 'y') ADVANCE(50);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(83);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_doc_text);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(83);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(aux_sym_type_token1);
      if (lookahead == '*') ADVANCE(86);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(85);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(87);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(aux_sym_type_token1);
      if (lookahead == '*') ADVANCE(86);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == '!') ADVANCE(85);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(87);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(aux_sym_type_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(87);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(89);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_description);
      if (lookahead == '*') ADVANCE(91);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(90);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(92);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_description);
      if (lookahead == '*') ADVANCE(91);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == '!') ADVANCE(90);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(92);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_description);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(92);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 36},
  [2] = {.lex_state = 6},
  [3] = {.lex_state = 6},
  [4] = {.lex_state = 6},
  [5] = {.lex_state = 6},
  [6] = {.lex_state = 6},
  [7] = {.lex_state = 6},
  [8] = {.lex_state = 6},
  [9] = {.lex_state = 6},
  [10] = {.lex_state = 36},
  [11] = {.lex_state = 36},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 36},
  [16] = {.lex_state = 36},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 90},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 90},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 90},
  [30] = {.lex_state = 90},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 1},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_STAR_SLASH] = ACTIONS(1),
    [anon_sym_ATfunction] = ACTIONS(1),
    [anon_sym_ATclass] = ACTIONS(1),
    [anon_sym_ATparam] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_ATproperty] = ACTIONS(1),
    [anon_sym_ATreturns] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(18),
    [sym_doc_comment] = STATE(11),
    [aux_sym_source_file_repeat1] = STATE(11),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_SLASH_STAR_STAR] = ACTIONS(5),
  },
  [STATE(2)] = {
    [sym_function_tag] = STATE(3),
    [sym_class_tag] = STATE(3),
    [sym_param_tag] = STATE(3),
    [sym_property_tag] = STATE(3),
    [sym_returns_tag] = STATE(3),
    [aux_sym_doc_comment_repeat1] = STATE(3),
    [anon_sym_STAR_SLASH] = ACTIONS(7),
    [anon_sym_ATfunction] = ACTIONS(9),
    [anon_sym_ATclass] = ACTIONS(11),
    [anon_sym_ATparam] = ACTIONS(13),
    [anon_sym_ATproperty] = ACTIONS(15),
    [anon_sym_ATreturns] = ACTIONS(17),
    [sym_doc_text] = ACTIONS(19),
  },
  [STATE(3)] = {
    [sym_function_tag] = STATE(4),
    [sym_class_tag] = STATE(4),
    [sym_param_tag] = STATE(4),
    [sym_property_tag] = STATE(4),
    [sym_returns_tag] = STATE(4),
    [aux_sym_doc_comment_repeat1] = STATE(4),
    [anon_sym_STAR_SLASH] = ACTIONS(21),
    [anon_sym_ATfunction] = ACTIONS(9),
    [anon_sym_ATclass] = ACTIONS(11),
    [anon_sym_ATparam] = ACTIONS(13),
    [anon_sym_ATproperty] = ACTIONS(15),
    [anon_sym_ATreturns] = ACTIONS(17),
    [sym_doc_text] = ACTIONS(23),
  },
  [STATE(4)] = {
    [sym_function_tag] = STATE(4),
    [sym_class_tag] = STATE(4),
    [sym_param_tag] = STATE(4),
    [sym_property_tag] = STATE(4),
    [sym_returns_tag] = STATE(4),
    [aux_sym_doc_comment_repeat1] = STATE(4),
    [anon_sym_STAR_SLASH] = ACTIONS(25),
    [anon_sym_ATfunction] = ACTIONS(27),
    [anon_sym_ATclass] = ACTIONS(30),
    [anon_sym_ATparam] = ACTIONS(33),
    [anon_sym_ATproperty] = ACTIONS(36),
    [anon_sym_ATreturns] = ACTIONS(39),
    [sym_doc_text] = ACTIONS(42),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 1,
    ACTIONS(45), 7,
      anon_sym_STAR_SLASH,
      anon_sym_ATfunction,
      anon_sym_ATclass,
      anon_sym_ATparam,
      anon_sym_ATproperty,
      anon_sym_ATreturns,
      sym_doc_text,
  [10] = 1,
    ACTIONS(47), 7,
      anon_sym_STAR_SLASH,
      anon_sym_ATfunction,
      anon_sym_ATclass,
      anon_sym_ATparam,
      anon_sym_ATproperty,
      anon_sym_ATreturns,
      sym_doc_text,
  [20] = 1,
    ACTIONS(49), 7,
      anon_sym_STAR_SLASH,
      anon_sym_ATfunction,
      anon_sym_ATclass,
      anon_sym_ATparam,
      anon_sym_ATproperty,
      anon_sym_ATreturns,
      sym_doc_text,
  [30] = 1,
    ACTIONS(51), 7,
      anon_sym_STAR_SLASH,
      anon_sym_ATfunction,
      anon_sym_ATclass,
      anon_sym_ATparam,
      anon_sym_ATproperty,
      anon_sym_ATreturns,
      sym_doc_text,
  [40] = 1,
    ACTIONS(53), 7,
      anon_sym_STAR_SLASH,
      anon_sym_ATfunction,
      anon_sym_ATclass,
      anon_sym_ATparam,
      anon_sym_ATproperty,
      anon_sym_ATreturns,
      sym_doc_text,
  [50] = 3,
    ACTIONS(55), 1,
      ts_builtin_sym_end,
    ACTIONS(57), 1,
      anon_sym_SLASH_STAR_STAR,
    STATE(10), 2,
      sym_doc_comment,
      aux_sym_source_file_repeat1,
  [61] = 3,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR_STAR,
    ACTIONS(60), 1,
      ts_builtin_sym_end,
    STATE(10), 2,
      sym_doc_comment,
      aux_sym_source_file_repeat1,
  [72] = 2,
    ACTIONS(62), 1,
      anon_sym_LBRACE,
    STATE(23), 1,
      sym_type,
  [79] = 2,
    ACTIONS(64), 1,
      anon_sym_LBRACE,
    STATE(21), 1,
      sym_type,
  [86] = 2,
    ACTIONS(64), 1,
      anon_sym_LBRACE,
    STATE(22), 1,
      sym_type,
  [93] = 1,
    ACTIONS(66), 2,
      ts_builtin_sym_end,
      anon_sym_SLASH_STAR_STAR,
  [98] = 1,
    ACTIONS(68), 2,
      ts_builtin_sym_end,
      anon_sym_SLASH_STAR_STAR,
  [103] = 1,
    ACTIONS(70), 1,
      sym_identifier,
  [107] = 1,
    ACTIONS(72), 1,
      ts_builtin_sym_end,
  [111] = 1,
    ACTIONS(74), 1,
      sym_identifier,
  [115] = 1,
    ACTIONS(76), 1,
      aux_sym_type_token1,
  [119] = 1,
    ACTIONS(78), 1,
      sym_identifier,
  [123] = 1,
    ACTIONS(80), 1,
      sym_identifier,
  [127] = 1,
    ACTIONS(82), 1,
      sym_description,
  [131] = 1,
    ACTIONS(84), 1,
      anon_sym_DASH,
  [135] = 1,
    ACTIONS(86), 1,
      sym_identifier,
  [139] = 1,
    ACTIONS(88), 1,
      anon_sym_DASH,
  [143] = 1,
    ACTIONS(90), 1,
      sym_description,
  [147] = 1,
    ACTIONS(92), 1,
      anon_sym_RBRACE,
  [151] = 1,
    ACTIONS(94), 1,
      sym_description,
  [155] = 1,
    ACTIONS(86), 1,
      sym_description,
  [159] = 1,
    ACTIONS(96), 1,
      anon_sym_RBRACE,
  [163] = 1,
    ACTIONS(98), 1,
      aux_sym_type_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(5)] = 0,
  [SMALL_STATE(6)] = 10,
  [SMALL_STATE(7)] = 20,
  [SMALL_STATE(8)] = 30,
  [SMALL_STATE(9)] = 40,
  [SMALL_STATE(10)] = 50,
  [SMALL_STATE(11)] = 61,
  [SMALL_STATE(12)] = 72,
  [SMALL_STATE(13)] = 79,
  [SMALL_STATE(14)] = 86,
  [SMALL_STATE(15)] = 93,
  [SMALL_STATE(16)] = 98,
  [SMALL_STATE(17)] = 103,
  [SMALL_STATE(18)] = 107,
  [SMALL_STATE(19)] = 111,
  [SMALL_STATE(20)] = 115,
  [SMALL_STATE(21)] = 119,
  [SMALL_STATE(22)] = 123,
  [SMALL_STATE(23)] = 127,
  [SMALL_STATE(24)] = 131,
  [SMALL_STATE(25)] = 135,
  [SMALL_STATE(26)] = 139,
  [SMALL_STATE(27)] = 143,
  [SMALL_STATE(28)] = 147,
  [SMALL_STATE(29)] = 151,
  [SMALL_STATE(30)] = 155,
  [SMALL_STATE(31)] = 159,
  [SMALL_STATE(32)] = 163,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [25] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_doc_comment_repeat1, 2, 0, 0),
  [27] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_doc_comment_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [30] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_doc_comment_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [33] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_doc_comment_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [36] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_doc_comment_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [39] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_doc_comment_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [42] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_doc_comment_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [45] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_param_tag, 5, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_class_tag, 2, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_tag, 2, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_returns_tag, 3, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_property_tag, 5, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [57] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_doc_comment, 2, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_doc_comment, 3, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [72] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 3, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_api_doc(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
